baseurl = "http://www.inagroindonesia.com"
languageCode = "en-us"
title = "Inagro Indonesia"
canonifyUrls = "true"
theme = "landing-page-hugo"
publishDir = "docs"

[params]
    description = "Changing the World through Education"
    custom_css = ["css/local.css"]
