baseurl = "http://www.inagroindonesia.com/en"
languageCode = "id-IND"
title = "Inagro Indonesia"
canonifyUrls = "true"
theme = "landing-page-hugo"
publishDir = "docs"
googleAnalytics = "UA-98287421-1"


[params]
    description = "Changing the World through Education"
    custom_css = ["css/local.css"]
    locale = "id-IND"
