baseurl = "https://inagroindonesia.github.io/inagro-site/"
languageCode = "en-us"
title = "Inagro Indonesia"
canonifyUrls = "true"
theme = "landing-page-hugo"
publishDir = "docs"
contentDir = "content_en"
menu = "main"
googleAnalytics = "UA-98287421-1"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
    description = "Changing the World through Education"
    custom_css = ["css/local.css"]
    locale = "en-US"
    HomePage = "index_en.html"
    nextHomePage = "index.html"


[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:marketing@inagroindonesia.com"

[[params.social]]
    title = "instagram"
    icon = "instagram"
    url = "https://www.instagram.com/inagroindonesia/"
